# Generated by Django 6.0.6 on 2026-06-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('frais_plateforme', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('mode', models.CharField(choices=[('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('carte', 'Carte bancaire')], default='orange', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
