# Generated by Django 6.0.6 on 2026-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('prestataire', 'Prestataire')], max_length=20, null=True),
        ),
    ]
