# Generated by Django 6.0.6 on 2026-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='disponible',
        ),
        migrations.AddField(
            model_name='service',
            name='favoris_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('suspendu', 'Suspendu')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='vues_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
